apiVersion: extensions/v1
kind: Ingress
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  rules:
  - host: stage-myapp.example.local
    http:
      paths:
      - backend:
          serviceName: myapp
          servicePort: 80
